### ISSUE TITLE
Docker permissions issue

### ISSUE THREAD

**Issue by aaronleopold** [aaronleopold/stump#56]
Docker seems to create stump's config directory, on the host machine, with root privilege, making root the owner. This becomes a big problem during runtime, as stump won't have permissions to modify/access the config folder, which causes a ton of errors.

Changing the permissions manually fixes this, but this is really not ideal. 

I have only been able to reproduce this issue on Linux (both a dedicated install, as well as WSL). Config folder must not already be present (`~/.stump`), otherwise issue won't occur.

**Comment by oliviacarino** [comment]
Hey! Just to clear things up, the goal is to give stump only the permissions to the config directory and not create it within the host machine? 

Can I take on this issue?

**Comment by aaronleopold** [comment]
Hi! So to clarify, when the config folder (e.g. `~/.stump`) does not exist on the host machine, Docker creates it with the root user as the owner. So if I had this compose file:

```yml
version: '3.3'
services:
  stump:
    image: aaronleopold/stump-preview
    ports:
      - '10801:10801'
    user: '1000:1000'
    volumes:
      - /Users/aaronleopold/Documents/Stump:/data
      - /Users/aaronleopold/.stump:/config
```

When I run `docker compose up`, docker creates `/Users/aaronleopold/.stump` with root and Stump internally throws a bunch of permissions errors, e.g. cannot create database or cannot create log file, etc. So the goal is to figure out how to get docker to create that config folder on the host machine **not** owned by root. Does that make sense?

If you still would like it, feel free to take it on! Keep in mind, if it is for hacktoberfest **don't make the PR until it actually starts**. Otherwise, I am not sure it will be counted towards your total.
